### PR TITLE
Add saturation vapor pressure module and optimizations to share code.

### PR DESCRIPTION
**Pull request by quantheory**
This PR has two related goals:
1. Create a module with a superset of the the functionality in CAM's `wv_sat_methods` and CLUBB's `saturation`, combined with a more flexible set of lookup tables, and move it into CIME. This module is called `shr_wv_sat_mod`. For comparison, you can see `src/physics/cam/wv_sat_methods.F90` and `src/physics/clubb/saturation.F90` in CAM, but the differences are large enough that a diff may not be that helpful.
2. Add changes suggested by Chris Kerr for optimization of the MG2 microphysics, especially by speeding up transcendental functions when using Intel 15. Chris made some significant changes to `wv_sat_methods` in the process, which have been translated to `shr_wv_sat_mod` here. (This was not exactly trivial, but by following some of Chris's suggestions I was able to check that vector functions in the new module still vectorize, and are sped up significantly, as long as the options added in `Depends.intel` are used.)

Note that the `seq_infodata_inparm` now controls `shr_wv_sat_mod`, rather than a CAM namelist controlling it. This is unfortunate for a minority of CAM users who are used to the existing CAM namelist options, but this change seems unavoidable with `shr_wv_sat_mod` being outside of CAM. (See the commit messages for a bit more on why I moved this in the first place.)

For the moment, I have left lookup tables off by default in the saturation code, using the `wv_sat_use_tables` namelist option. The general feeling in AMP and ACOM is that these lookup tables may be acceptable, but not desirable, given that lookup tables have frequently caused large numerical errors or crashes in CAM and especially WACCM. However, lookup tables seem to significantly speed up the run in CAM4/CAM5, as well as the current versions of both CLUBB and UNICON.

Most likely we will want to turn the tables on by default for CAM4/CAM5/CAM5.4 compsets (unless these compsets are removed entirely before CESM 2). We can avoid using them for CAM5.5 and higher if enough of the code is vectorized that performance becomes competitive with lookup tables on our supported machines.

### CODE REVIEW

**Comment by quantheory** [comment]
Oh, and I have followed the csm_share naming convention in the module name, but I haven't added `shr_` to the front of the methods inside the module. Part of the reason for this is that many of the names are already quite long. Adding the `shr` makes them harder to type, and isn't really necessary given that the `wv_sat` prefix already makes it easy to tell where these functions come from.

Another part of the reason is that, on the CAM branch where I'm actually using the vector routines from the updated module, it was already a pain to rename the module and some of the functions, because there are quite a few references to them. I don't really want to have to rename _all_ of the functions once more, because I am lazy.

**Comment by quantheory** [comment]
Oh, and this code is intended to be compilable outside of CIME entirely, which is one reason why it does not directly use `shr_kind_mod` and `shr_const_mod`. I could work around this with `#ifdef`, but it seemed better to just hard-code double precision and to set constants at run time. If there's a big enough benefit, though, I could use `#ifdef`s instead.

**Comment by quantheory** [comment]
I don't really know who should review this, but I think that @jedwards4b probably wants to see at least the `Depends.intel` and `shr_spfn_mod.F90` changes. Maybe @mvertens or @apcraig can comment on the addition to the driver namelist.

**Comment by quantheory** [comment]
Hey @apcraig, can you review this?

**Comment by apcraig** [comment]
I had a look at the changes and everything seems pretty reasonable.  I do think all the subroutines should have a shr_ on the front of them and that should be done now.  I know it's a pain and it's easier to be lazy, but this is a reasonable coding convention and it provides insight about where the source code lives.  In particular, if someone sees a call to wv_sat_\* from cam and they want to "find" that code, it's going to take them a while.  if it's called shr_wv_sat_*, that's a huge clue where to find it.  All code in the csm_share/shr directory meets this standard and this code should too.  It also makes it more likely that the names will be unique when compiled and linked with different models.

I think that has to be changed before the code can be merged on the trunk.

**Comment by quantheory** [comment]
@apcraig

I guess that there are two other considerations now that I should mention:
1. As mentioned in #18, I don't think actually think that `csm_share` should continue to exist in its present form, and I'm going to take a crack at dividing it pretty soon. I think that this will end up as 2-3 separate libraries, and in the long run I don't think that it makes sense that the `shr` prefix should be shared by all of them.
2. I'm also pushing for this _specific_ module to be used outside of CIME entirely (e.g. in CLUBB outside of CAM). In that situation, there is no `csm_share`, and the `shr` prefix doesn't actually tell you anything useful.

Given those factors, I'm tempted to actually go the other way, and remove `shr` from the file/module name entirely, at least until the `csm_share` reorganization solidifies enough that we know what the new naming conventions will be. I see this as something of a temporary situation where this specific module isn't really part of `csm_share` as a unified whole, but there's just not another location to put it right now, to get it in a public location and usable by multiple components.

**Comment by apcraig** [comment]
It really depends how this module is going to be used.  If it may be 
used by multiple models,
then it probably belongs in csm_share and be called shr_something. If 
it's something that
should  be part of CLUBB, then I agree that it's fine for it to sit in 
csm_share temporarily
until it gets moved to CLUBB and then the naming convention should be 
consistent with whatever
CLUBB requires.

I'm not sure what the motivation is to split up csm_share at this 
point.  If some files belong to
a single model, that's fine to move them to wherever they do belong.  
But, I don't think we should be
adding a bunch more complexity to the Filepaths and build by splitting 
up csm_share in a way
that suggests some are for atm models, others just for CAM, and others 
for different models.
In my opinion, CAM files belong in CAM.  shared files belong in 
csm_share.  And there need not
be a multitude of directories that go beyond that.  I don't see any need 
for more directories.

tony........

**Comment by jedwards4b** [comment]
The argument for splitting up csm_share is valid I agree that it should be divided into a library that doesn't have any other internal dependancies and one (or more) that does.

But I also agree that prefixing modules in a way that allows us to quickly identify where they are located is a useful feature.   Can we find a compromise here that will allow us to complete this merge?

**Comment by apcraig** [comment]
It would be helpful to me to understand what is driving the split in 
csm_share.
If it's because a few files don't "use" any other files, why is it 
helpful that they
get split out?  There aren't that many files in csm_share yet. Adding more
directories (don't we already have enough!) seems like it would just 
increase
the complexity of the directory structure and add to the confusion of where
things are.

tony.......

**Comment by jedwards4b** [comment]
The split is motivated by the fact that we have code in that library such as shr_math_mod or
shr_kind_mod that can be made available and used as a standalone library independent of 
cesm or cime and other code,  shr_pio_mod, shr_flux_mod that are specific to cesm or cime.   We want 
to be able to build a library of share code that doesn't have this limitation so that for example standalone tests in pio or homme can use the shr code they need to use without having to copy and paste certain parts of csm_share as they are currently doing.

**Comment by rljacob** [comment]
I'd like to see that kind of code (kinds, math) made in to a library independent of climate modeling.  Finding the right way to package all this is important but maybe not for settling this PR.

**Comment by bandre-ucar** [comment]
Sean explained the reasoning very clearly in the link he sent on Monday:

https://github.com/CESM-Development/cime/issues/18

Personally, I don’t like ’shr_'. I’d prefer it was removed and replaced with something meaningful for each group in Seans list.

Ben

**Comment by apcraig** [comment]
ok, i hadn't seen issue 18 before.

that clarifies the motivation.  the problem with splitting these things 
up is that
where they belong is often not static.  and people are going to end up 
dropping
code in the wrong place.  we have some history of moving code back and forth
between shr and drv/shr and other places.  at one time, code might
belong in one directory and after some code cleanup or some new code, it
might need to be moved somewhere else.

in my opinion, our processes and requirements are not robust enough to
do this in a way that will be maintained.  i also don't think we should 
change
a long standing standard just because someone doesn't like the shr_
standard or the name of csm_share.  could it be different or better, 
probably.
would it fundamentally improve CESM, i doubt it.  would it confuse people,
yes almost certainly for a while.  for all those reasons, i feel this is 
just an
exercise in refactoring that brings little benefit to the project.

i understand the motivation in wanting to be able to build "low level"
code that doesn't depend on anything else.  maybe we can add a Filelist
that a Makefile could use to the csm_share directory that lists the files
that can be built without other dependencies.  It seems like there are other
ways to support this feature without splitting everything apart and renaming
everything.

tony.......

**Comment by jedwards4b** [comment]
This conversation has diverged from the context of the current pull request.   Can
we move further discussion to https://github.com/CESM-Development/cime/issues/18 and complete this pull?   Sean can you use the current shr_ stuff now and possible move it in a later tag?

**Comment by quantheory** [comment]
> Sean can you use the current shr_ stuff now and possible move it in a later tag?

Probably? I'm not sure what you mean.

**Comment by jedwards4b** [comment]
I would like to complete this pull request and address the split of
csm_share separately.

On Thu, Jun 4, 2015 at 8:35 PM, Sean Patrick Santos <
notifications@github.com> wrote:

> Sean can you use the current shr_ stuff now and possible move it in a
> later tag?
> 
> Probably? I'm not sure what you mean.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/pull/17#issuecomment-109139249.

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Pull request merged**
