### PR TITLE
New version of MCT needed for CAM

### PR DESCRIPTION
**Pull request by gold2718**
The new version of MCT includes the 8-byte IndexSort routine needed by the new CAM infrastructure.
Ran CIME standalone tests on Yellowstone.

### CODE REVIEW

**Comment by rljacob** [comment]
There's also now a MCT_2.9.0 tag (the actual 2.9 release, not a rc) if you want to include that.

**Comment by gold2718** [comment]
CSEG: Should I rebase this on the tag (instead of the rc)? That way, we get the new MCT tag along with what I need for CAM.

**Comment by jedwards4b** [comment]
Yes - i think that's a good idea.

On Thu, Jun 25, 2015 at 9:56 AM, goldy notifications@github.com wrote:

> CSEG: Should I rebase this on the tag (instead of the rc)? That way, we
> get the new MCT tag along with what I need for CAM.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/pull/30#issuecomment-115303181.

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by gold2718** [comment]
Closing this pull request. New one will just be new MCT import.

**Pull request closed without merging**
