### PR TITLE
Fix unit test netCDF detection and NAG support.

### PR DESCRIPTION
**Pull request by quantheory**
These were the changes that I needed to be able to get the unit tests to build and pass with NAG on my CGD desktop. Note two possible sources of breakage:
1. NAG on goldbach is broken by the removal of the `-kind=byte` flag. I don't think that this is a big problem because goldbach is being decommissioned this week. When we add a port to the successor machine, we'll have to make sure to link to the appropriate library, and everything should be well again. We should also bump to NAG 6.0. (I don't know if ISG even plans to keep NAG 5.3.1 around, but regardless, I don't think there's any real reason for us to support the older version given that this is our testing compiler.)
2. My changes to FindNETCDF might break existing machines. It's not clear to me if there's really much of a risk here or not; I can test yellowstone and mira, but who knows what will happen on other machines. The changes are to fall back on using `$NETCDF` as a hint for the netCDF directory, which I think is pretty safe, and looking for libcurl if netCDF is using DAP, which may or may not be a problem.

### CODE REVIEW

**Comment by jedwards4b** [comment]
Hi Sean,

If we build all of the libraries consistently I don't think we should need
the kind=byte flag?

On Tue, Jun 16, 2015 at 3:00 PM, Sean Patrick Santos <
notifications@github.com> wrote:

> Assigned #25 https://github.com/CESM-Development/cime/pull/25 to
> @jedwards4b https://github.com/jedwards4b.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/pull/25#event-332531357.

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by quantheory** [comment]
Yep, that's the idea.

**Comment by jedwards4b** [comment]
Is this compatible with #28 ?

**Comment by quantheory** [comment]
I believe so. I rebased the one on top of the other, on the branch where I am working on hobart.

**Pull request merged**
