### PR TITLE
Vbs cime4.1.2

### PR DESCRIPTION
**Pull request by fvitt**
Please pull in these mods for chemistry

### CODE REVIEW

**Comment by jedwards4b** [comment]
Is this change compatible with current component models or does it require new components?

**Comment by fvitt** [comment]
It is compatible with current components. However, it changes answers for
some complicated tropospheric chemistry configurations.

**Comment by fvitt** [comment]
Can a new tag be made so that we can test these changes in alpha02f?

**Comment by jedwards4b** [comment]
Hi Francis,

You don't need to make a tag for that, just replace the svn checkout of
cime with a git clone and put it at the head of master.
You're also welcome to make a tag yourself if you would prefer.

On Fri, Oct 30, 2015 at 10:00 AM, fvitt notifications@github.com wrote:

> Can a new tag be made so that we can test these changes in alpha02f?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/pull/271#issuecomment-152565805
> .

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by fvitt** [comment]
Jim,

I believe what you describe is a way to test in a sandbox.  I would to
include my change in the alpha02f tag which would require a new tag. Can
this not be included in the alpha02f tag?

Thanks

**Pull request merged**
