### PR TITLE
Point to a pFUnit build in CESMDATAROOT for yellowstone

### PR DESCRIPTION
**Pull request by billsacks**
We had been using a pFUnit build in my home directory; at Jim's
request, I am moving this into CESMDATAROOT/tools

Test suite: cime unit tests on yellowstone/caldera
Test baseline: N/A
Test namelist changes: N/A
Test status: All passed

Fixes: None

Code review: None yet

### CODE REVIEW

**Comment by billsacks** [comment]
I should note: I have left the old pFUnit build in place in my home directory, so unit tests run with older versions of cime will continue to work.

**Comment by bandre-ucar** [comment]
Can you please add new fields PFUNIT_GIT_{REPO| && HASH} or something similar that point to the exact supported version of pfunit. It's critical for reproducible tests, and I have an in-progress hack that automatically downloads and builds pfunit.

**Comment by billsacks** [comment]
@bandre-ucar : I see the value in what you are suggesting. But can you move this to a separate issue? I can't speak for what Sean has done, but for the yellowstone build that I have done, I grabbed pFUnit from http://sourceforge.net/projects/pfunit/files/latest/download, where the version is documented simply as:

$ cat VERSION 
pFUnit 3.1 master

So I think that doing what you're suggesting would involve redoing the build with a snapshot from the git repo, right? I'm thinking that that change shouldn't stand in the way of this current pull request, which I'm making at Jim's request.

**Comment by bandre-ucar** [comment]
ok.

**Pull request merged**
