### PR TITLE
Change ocn(1) to ice(1) in call to seq_map_init_rcfile for Rg2i.

### PR DESCRIPTION
**Pull request by billsacks**
Jeremy Fyke noticed this bug. It shouldn't have any effect, since the ocn and
ice resolutions are always the same. But this seems worth fixing anyway.

I have not run any testing on this change. Once someone signs off on it, I'll run the cime tests then bring it to master.

### CODE REVIEW

**Comment by billsacks** [comment]
thanks, I'll run the tests & bring to master

**Comment by JeremyFyke** [comment]
Thanks @billsacks for following this up.

**Comment by jedwards4b** [comment]
I'm going to go ahead and merge this - it'll be tested with beta 05 testing.

**Comment by billsacks** [comment]
Thanks. For what it's worth, I just checked the cime test suite (prealpha drv tests on yellowstone) and it came back clean. Although, to be honest, I'm not sure this line of code is exercised in any of these tests - or anywhere else in the system currently, for that matter: I think @JeremyFyke is the only one who is exercising it.

**Pull request merged**
