### PR TITLE
Move lnd <-> glc coupling into coupler

### PR DESCRIPTION
**Pull request by billsacks**
Previously, as far as the coupler was concerned, glc existed on the lnd
grid. Coupling between glc and lnd was handled by the "glint" package of
CISM. However, this coupling had a number of limitations, such as only working
with a regular lat-lon land grid, and only doing bilinear (non-conservative)
interpolation from lnd -> glc.

The changes on this branch move this coupling into the coupler. So now GLC is
treated more similarly to other components: The coupler does the regridding
between lnd <-> glc. However, this coupling is unique in its use of multiple
elevation classes. Thus, custom coupling routines have been added to carry out
this coupling. These coupling routines are similar (conceptually) to those in
CISM's glint, but have some distinct differences. For details, see
https://drive.google.com/drive/u/0/folders/0B4hbp0iL0ls1aWR4OHkwVEFsUWM.

Note that this change means that there is no longer a CISM_GRID variable:
GLC_GRID is now used for the ice sheet grid (rather than the land grid).

Also, add glc_elevclass_mod for storing and retrieving information about GLC
elevation classes, and use that where appropriate (in dlnd as well as
driver/coupler).

These changes require updated versions of CISM and CLM.

Test suite: full yellowstone prealpha & prebeta test suites (including all
            compsets, not just the cime standalone tests)
Test baseline: cesm1_4_alpha06c
Test namelist changes: changes namelists for all tests
Test status: changes answers for all compsets with CISM (TG, IG, FG, BG), due to
             having new methods for the lnd <-> glc coupling.

```
         Also changes answers for all X compsets, due to a change in
         coupling fields
```

Some tests failed, which also failed in cesm1_4_alpha06c + cime master (and thus
were presumed to not be due to these changes). A few other tests timed out
because I specified a shorter wall-clock limit (2:00). Other than that, all
tests passed.

Code reviews: Tony Craig

### CODE REVIEW

**Comment by rljacob** [comment]
What kind of updates are needed for CLM?   I'm trying to update ACME's version of CIME.

**Comment by billsacks** [comment]
@rljacob - thanks for your work on this! The changes needed to CLM are pretty small, and are restricted to this CLM tag:

https://svn-ccsm-models.cgd.ucar.edu/clm2/trunk_tags/clm4_5_1_r118

(can compare with clm4_5_1_r117).

There are much more extensive changes needed in CISM. But my understanding is that CISM tests currently do not run in ACME (it's a chicken and egg problem: they need these CIME changes in order to get CISM working again), so pulling in the latest CISM could be deferred.

**Comment by rljacob** [comment]
Turns out I as able to run an I case in ACME without those CLM changes and with cime2.0.12.  Does that sound right?

**Comment by billsacks** [comment]
You might be able to run an I case (e.g., ICLM45), but I would be surprised if you were able to run an IG case (e.g., IGCLM45) - at least, one that gave any sensible results. However, given that IG cases are broken for other reasons (as Matt Hoffman and Doug Jacobsen are aware), I don't think you'll be able to test that right now. Again, chicken and egg here.

**Pull request merged**
