### PR TITLE
In cprnc, treat differences in variable dimension sizes as a failure

### PR DESCRIPTION
**Pull request by billsacks**
Previously, files were considered identical even if they had variables
whose dimension sizes differed (these variables were ignored). Now this
is treated as a difference.

Dimension size differences result in the following line being printed:

DIMSIZEDIFF varname

In addition, the final reporting includes a separate count for the
number of variables whose dimension sizes differ. The number of
variables not analyzed for other reasons is counted separately, and the
final reporting also includes the total count of variables that could
not be analyzed for all reasons (this is the same as the old count of
variables that could not be analyzed).

I have also updated component_write_comparefail.pl and
summarize_cprnc_diffs to report these DIMSIZEDIFF results.

Additional changes in this PR are:

(1) IMPORTANT: Changed cprnc path on yellowstone to point to a new
location. The old location came from an svn checkout of the old cprnc
repository. The new location is a full cime clone, since cprnc is now
included in cime. I have built cprnc in this new location. The old
location is still there for backwards compatibility.

(2) Get cprnc tests to pass in debug mode with gfortran (on my mac)

(3) Include correctly-named Macros file in the cprnc Makefile

(4) Update cprnc README to document correct configure command

(5) Minor changes to the cprnc run_tests script

Test suite: yellowstone drv prealpha
Test baseline: cesm1_5_alpha04d
Test namelist changes: none
Test status: bit for bit

In addition, ran:

(a) cprnc run_tests script; results the same as before, except that all
runs now include an output like this:

```
                and      0 had different dimension sizes
```

and there is a new lon_differs test whose behavior differs from before
(now reporting the files as DIFFERENT)

(b) "unit" tests listed in summarize_cprnc_diffs (checked results manually)

Fixes: None

User interface changes?: No

Code review: None yet

### CODE REVIEW

**Comment by billsacks** [comment]
@sholly @mvertens @jedwards4b : I'd like your opinion on a few things here:

(1) Do you see any problems with changing the behavior of cprnc in this way? Will it cause comparisons to fail that should be considered PASSes? i.e., are there ever times when dimension sizes differ but you want the files to be considered identical?

(2) Do you see any problems with pointing to the new cprnc location on yellowstone - in a cime clone that I have put in $CESMDATAROOT/tools? We'll also want to update other machines in a similar way, I suppose. 

(3) Note that, if files have different dimension sizes, this will print DIMSIZEDIFF for every variable that differs... often that will be all the variables in the file. (As opposed to checking the dimensions themselves). To me this seems okay... it just means there is some extra noise in the output... but the plus side is that you explicitly see which variables can / cannot be compared.

As an aside: this exercise inspired me to bump my python cprnc script to the top of my list (starting today)... I think I should be able to reproduce the essential functionality pretty quickly.

**Comment by sholly** [comment]
This all looks excellent, .holding off on the merge to get input from Mariana and Jim, but I see no reason why this can't be included in beta04

**Comment by jedwards4b** [comment]
On Dec 21, 2015 11:04 AM, "Bill Sacks" notifications@github.com wrote:

> @sholly @mvertens @jedwards4b : I'd like your opinion on a few things
> here:
> 
> (1) Do you see any problems with changing the behavior of cprnc in this
> way? Will it cause comparisons to fail that should be considered PASSes?
> i.e., are there ever times when dimension sizes differ but you want the
> files to be considered identical?
> 
> I don't think so.
> 
> (2) Do you see any problems with pointing to the new cprnc location on
> yellowstone - in a cime clone that I have put in $CESMDATAROOT/tools? We'll
> also want to update other machines in a similar way, I suppose.

Sounds fine.

> (3) Note that, if files have different dimension sizes, this will print
> DIMSIZEDIFF for every variable that differs... often that will be all the
> variables in the file. (As opposed to checking the dimensions themselves).
> To me this seems okay... it just means there is some extra noise in the
> output... but the plus side is that you explicitly see which variables can
> / cannot be compared.
> 
> As an aside: this exercise inspired me to bump my python cprnc script to
> the top of my list (starting today)... I think I should be able to
> reproduce the essential functionality pretty quickly.

I'm concerned about the interoperability of python with netcdf.   It seems
like this had been an ongoing problem.   But if you've gotta do it I
suppose cprnc is a good place to start.      Another question that comes up
for me is : with all the stuff we have to do is rewriting cprnc really a
priority?

**Comment by billsacks** [comment]
> I'm concerned about the interoperability of python with netcdf.   It seems
> like this had been an ongoing problem.   But if you've gotta do it I
> suppose cprnc is a good place to start.      Another question that comes up
> for me is : with all the stuff we have to do is rewriting cprnc really a
> priority?

I'm going to see what I can get done in a short amount of time. If this grows to be bigger than I expected, I'll put it on hold.

**Pull request merged**
