### PR TITLE
fix testing issues on mira and yellowstone

### PR DESCRIPTION
**Pull request by jedwards4b**
On mira the cimeroot was not initialized in the Batch class.
On yellowstone the syntax to set rootpe was incorrect in ConfigPes.pm

### CODE REVIEW

**Comment by bandre-ucar** [comment]
'Fix issues on xxx' isn't at all informative to anyone other than the original author, and I'd bet it isn't going to be informative to you in 6 months. It only takes a minute to describe the bugs you are fixing and makes the project history much more useful. This is particularly important now that we are trying to collaborate with other non-cesm users of cime who may encounter the same bugs when they port to another machine...

**Comment by rljacob** [comment]
I was just going to ask what the issue on Mira was.

**Comment by jedwards4b** [comment]
Rob - most of the issues you are going to see for the next few days are related to the cime3.0 refactor and are not relevant to older versions.

**Comment by rljacob** [comment]
Ok but I agree with Ben's comment.  The commit message when this gets merged should be understandable to you in 6 months.

**Pull request merged**
