### PR TITLE
mlevy/mapping build

### PR DESCRIPTION
**Pull request by mnlevy1981**
Update instructions for building mapping tools to reflect changes in CIME configure tool. Was able to build gen_domain, runoff_map, and map_field on yellowstone following these updated steps in bash, but it would be nice to have someone confirm that the csh instructions are correct as well (is `source` the correct command to read in `.env_mach_specific.csh`?)

Also, this should let us close issue #219

### CODE REVIEW

**Comment by mnlevy1981** [comment]
I should add that I haven't tested the special janus-only scripts for any of the tools... I just logged in for the first time in 15 months and will make sure everything compiles.

**Comment by jedwards4b** [comment]
Yes source is the correct command for both csh and bash.   Janus is not a
supported system.

On Mon, Oct 12, 2015 at 4:53 PM, Michael Levy notifications@github.com
wrote:

> I should add that I haven't tested the special janus-only scripts for any
> of the tools... I just logged in for the first time in 15 months and will
> make sure everything compiles.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/pull/226#issuecomment-147543327
> .

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by mnlevy1981** [comment]
I'll remove the Janus-specific scripts and instructions, and then comment when this is actually ready to be merged.

**Comment by mnlevy1981** [comment]
Pull request is ready for consideration! It would be nice if a csh-user would test that branch of the directions for me, I've confirmed that the bash instructions are okay.

**Pull request merged**
