### PR TITLE
force typename to serial for 1 pe runs

### LINKED ISSUE #290: Many single-processor tests fail with PIO error: "PNETCDF not enabled in the build"
Many single-processor tests – including about half of the tests in the aux_glc test suite – fail with a message like this:

   0: pio_support::pio_die:: myrank=          -1 : ERROR: ionf_mod.F90:         122 : PNETCDF not enabled in the build

SMS_D.f09_g16_gl5.TG.yellowstone_intel gives this traceback:

Image              PC                Routine            Line        Source  
cesm.exe           00000000028243E8  Unknown               Unknown  Unknown
cesm.exe           0000000001FA45BF  pio_support_mp_pi         120  pio_support.F90
cesm.exe           0000000001FA2C39  pio_utils_mp_bad_          97  pio_utils.F90
cesm.exe           00000000021577B9  ionf_mod_mp_creat         122  ionf_mod.F90
cesm.exe           0000000001F9EBF7  piolib_mod_mp_cre        2524  piolib_mod.F90
cesm.exe           000000000077F759  seq_io_mod_mp_seq         203  seq_io_mod.F90
cesm.exe           00000000006F1D36  seq_hist_mod_mp_s         228  seq_hist_mod.F90
cesm.exe           000000000043EA5D  cesm_comp_mod_mp_        3368  cesm_comp_mod.F90
cesm.exe           0000000000447B89  MAIN__                     93  cesm_driver.F90

These failing tests fail from both cesm1_5_beta01 and cesm1_5_beta02. I also notice that every PEA test in the beta02 series failed, and from spot-checking one of these (/glade/scratch/jshollen/PEA_P1_Ld3.T31_g37.X.yellowstone_pgi.GC.cesm15a02fbetapgi) it failed in the same way. 

I am labeling this as critical because I can not run any TG tests or production runs until this is resolved.

### PR DESCRIPTION
**Pull request by jedwards4b**
Fixes #290.

### CODE REVIEW

**Comment by billsacks** [comment]
@jedwards4b : Thanks for this quick fix. I'd like to add a comment in the code saying that this is a workaround for a bug in the scripts. Does that seem reasonable? If so, I can do it if you'd like, then do some testing and merge the PR. 

Also, since it sounds like this is just working around a scripts bug, I'd like to open a new (low-priority) issue on that scripts bug, so that it doesn't fall through the cracks - since fixing that seems to be the right long-term solution. Would you agree?

**Comment by jedwards4b** [comment]
It's not really a workaround for the scripts bug, it's something that
should be done anyway since a user can always go back and change an xml
setting that the scripts got right.   But opening another ticket on the
scripts issue is fine.

On Sun, Nov 8, 2015 at 12:21 PM, Bill Sacks notifications@github.com
wrote:

> @jedwards4b https://github.com/jedwards4b : Thanks for this quick fix.
> I'd like to add a comment in the code saying that this is a workaround for
> a bug in the scripts. Does that seem reasonable? If so, I can do it if
> you'd like, then do some testing and merge the PR.
> 
> Also, since it sounds like this is just working around a scripts bug, I'd
> like to open a new (low-priority) issue on that scripts bug, so that it
> doesn't fall through the cracks - since fixing that seems to be the right
> long-term solution. Would you agree?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/pull/291#issuecomment-154859334
> .

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by billsacks** [comment]
Okay, that sounds reasonable. But could you at least comment on why it doesn't work to use pnetcdf or netcdf4p when npes=1? I understand that you wouldn't expect to see any benefits from it, but I don't see why it's not allowed at all?

(I'm putting myself in the shoes of a maintenance programmer: I'd be tempted to delete these lines in the future unless there's some comment saying why they're needed.)

**Comment by billsacks** [comment]
I have confirmed that this fix allows all tests in the aux_glc test suite to pass.

But in thinking about this more, I'm wondering if the solution you implemented here is the right one. My thinking is that it can be confusing if the code ignores a setting set by the user, and so it's best if this sort of override only happens in cases where it's truly necessary. (As one example: If I wanted to test netcdf vs. pnetcdf on a simple case, by first seeing their different behavior with a single processor -- the solution you have implemented would cause confusion because my request to use pnetcdf would be ignored.)

I'm thinking that the real problem here is that the request to use pnetcdf at runtime is inconsistent with the logic for whether pnetcdf should be included in the build. If that's the case, then better solutions that I could see are:

(1) Catch the inconsistency at build-namelist time and give a meaningful error message to the user (telling them to rebuild with pnetcdf on). I realize that this will still require a workaround in the code until #292 is resolved - but we can label this as a temporary workaround that should be removed once #292 is resolved.

(2) If (1) isn't practical, then changing the logic in the code so that it triggers off of whether pnetcdf is enabled in the build – so that, if pnetcdf is enabled, then you can use pnetcdf, even if running with 1 proc.

I view the current solution as acceptable if (1) and (2) aren't practical... but feel that (1) or (2) would be better.

**Comment by billsacks** [comment]
@jedwards4b says that my suggestion (2) isn't practical, because the driver and share code don't know whether pnetcdf was included in the build.

So long-term we'll try for something like (1), but in the short-term we'll stick with the current workaround.

**Pull request merged**
