### PR TITLE
Ensemblefix

### PR DESCRIPTION
**Pull request by sholly**
```
create_clone now substitutes old cime/srcroot with new.

Fixed create_clone so that it substitutes the old cimeroot
and srcroot with the new directories in the cloned case.
Test suite: ERI, manual case clone
Test baseline: n/a
Test namelist changes: n/a
Test status: bit for bit

Fixes: #293

Code review: n/a
```

### CODE REVIEW

**Comment by jedwards4b** [comment]
Please add the -keepexe option to create_clone from issue #124 
also see if this resolves #58 and #73

**Comment by sholly** [comment]
add -keepexe to create_clone, Fix Casestatus, README.case

```
Added an option to create_clone to let the cloned case
reference the original case's exeroot, keep BUILD_COMPLETE as
TRUE.  create_clone will now append the create_clone name and args
to CaseStatus and README.case

Test suite: run manual clone case, ERI test, manual ensemble member run
Test baseline: n/a
Test namelist changes: n/a
Test status: expect BFB

Fixes: #58, #73, #124, #293

Code review: n/a
```

**Comment by jedwards4b** [comment]
Shouldn't you only print the warning banner if cimeroot1 is not equal to cimeroot2?
Otherwise this looks good and can be merged.

**Comment by sholly** [comment]
Yes, I'll fix..

**Pull request merged**
