### PR TITLE
Add `shr_RandNum_mod`.

### PR DESCRIPTION
**Pull request by quantheory**
`shr_RandNum_mod` is the Fortran interface for a collection of random number generator codes, collected and optimized by Chris Kerr (with some tweaks by yours truly). Much of the code is copied verbatim from outside sources, and I haven't reviewed, for instance, the dSFMT code in detail.

I wanted to put this up for review, because I've been sitting on it too long, but there are at least two things that should probably be resolved.

First, the interface module doesn't handle errors due to invalid inputs at all. It needs either error return codes or assert statements to deal with bad input strings, arrays that are the wrong size, etc. Any preferences on whether we use asserts or error codes?

Second, I still have to test this on Mira.

### CODE REVIEW

**Comment by quantheory** [comment]
I decided that I wasn't really satisfied with the interface, so I redid it. It's a bit more of an object oriented design now, and it's much easier to initialize and use a generator:

```
kiss_gen = ShrKissRandGen(kiss_seed)
call kiss_gen%random(array)
call kiss_gen%finalize()
```

No real change in the benchmarks, at least for Intel. Still don't have error handling, though.

Oddly, for the three generators added here, neither Intel nor PGI have the best performance on hobart. GNU beats Intel on the two Mersenne Twister codes by a wide margin, and NAG narrowly beats Intel for KISS (the generator that RRTMG actually uses). PGI is way behind everyone else.

**Comment by quantheory** [comment]
Still haven't addressed the issues in the OP above, but I've verified that at least on Intel (for the tests that I've done), this provides BFB answers when integrated into RRTMG. The branch for the RRTMG change is here:

https://svn-ccsm-models.cgd.ucar.edu/rrtmg/branches/shr_RandNum/

By the way, CC @chriskerr @brian-eaton @johnmauff, as I don't think that they watch the CIME issues that closely...

**Comment by rljacob** [comment]
Pinging a few ACME folks who might be interested:  @mrnorman, @worleyph, @singhbalwinder.

**Comment by jedwards4b** [comment]
Ready to merge.

**Comment by quantheory** [comment]
Made sure that the Makefile for the benchmark program can run on XLF. It doesn't look like we have any issues with any of these codes on big-endian systems like Mira.

**Pull request merged**
