### PR TITLE
Add a csm_share module for working with precipitation values

### PR DESCRIPTION
**Pull request by billsacks**
In a CLM branch that I'd like to bring to the trunk soon, we are repartitioning precipitation into rain/snow based on a (simple) algorithm that was already present in datm. In order to share this algorithm, I have extracted it into a new csm_share module. This pull request makes this change, and adds unit tests for this new module.

There is also an unrelated change - but one needed for the same CLM branch: adding a new CLM compset.

### CODE REVIEW

**Comment by billsacks** [comment]
This branch is based off of an older version of cime. There are conflicts in some unit test-related files. For now I needed this to be off of the older cime, because the newer cime changes answers. But I'll be sure to resolve these conflicts before bringing this branch to master.

**Comment by quantheory** [comment]
Purely out of curiosity, where would this be used in CLM? I'm wondering where it is, other than datm, that you have generic "precipitation" without knowing whether it's liquid or ice.

This looks fine to me. It might be good to mention a couple of things in the comments just in case, although they are probably pretty obvious:
1. This is especially for precipitation for the surface. (CAM of course uses very different formula in its parameterizations that have to partition particles in a grid cell into liquid/ice.)
2. This is presumably intended to provide a fraction of the **mass** (as opposed to a fraction of particle number, volume, droplet surface area, time/area of ground covered, psychological impact, television coverage...). Not that this is an exact or rigorous formula exactly, but we may as well be clear about what it is intended for.

**Comment by billsacks** [comment]
Thanks, Sean - I'll incorporate those comments.

As to where this will be used in CLM, this would probably cause much more contention than these software changes, but I'll hide behind the scientists making the decision on this one: A point that emerged from Breckenridge was that there are known problems with CAM's (and in particular, MG2's, I think) partitioning into rain vs. snow. In particular, it generates rain for temperatures below freezing. This causes problems in Greenland, where CAM sometimes rains  instead of snowing, affecting the evolution of the icesheet (and other things). Andrew hasn't found a way to fix this problem without breaking other things. So Andrew, as well as members of the land ice and land model working group, have suggested effectively ignoring the rain/snow partitioning generated by CAM, instead coming up with our own partitioning based on near-surface temperature. (And then doing the appropriate heat flux corrections to conserve energy due to this phase change.)

Even if that bias were fixed, this is still a capability we want in CLM: CLM has multiple elevation classes over glacier, so it will be very nice to have each elevation class have a different rain/snow partitioning based on its temperature.

That was probably a much longer answer than you were looking for :-)

**Comment by quantheory** [comment]
Oh! Actually, I may have an idea on how to fix that. But regardless, that was basically what I wanted to know. =)

**Comment by billsacks** [comment]
Merged in 044a79706492fa8213755c6d889c46e8c8d65c47

**Pull request closed without merging**
