### PR TITLE
Add a namelist option to increase the max size of the output matrix.

### PR DESCRIPTION
**Pull request by billsacks**
This applies to step3.

Also edit README to:
- add documentation of this option
- fix some typos
- add documentation of the need for grid_area on the scrip grid files

### CODE REVIEW

**Comment by billsacks** [comment]
This was needed in order to generate glc -> ocn mapping files. I set the new namelist variable to 50 for this purpose. An alternative would have been to change the code that determines esize, but adding a namelist option felt like a more robust solution - so that, in general, the smaller esize can be used, resulting in a significantly smaller memory footprint.

**Comment by mnlevy1981** [comment]
This looks great, but before I merge it to `master` I want to see if I can track down a better algorithm for determining S%n_s... I don't really like

```
    esize = (S%n_s/min(S%n_b,A%n_s)) * A%n_s * 2
    esize = int(float(esize) * 1.2)  ! this was necessary for some paleo mapping file - kauff
    esize = int(float(esize) * estsize_mult)
```

Especially with no indication of where the first `esize` comes from. So I'm going to do a quick search to see if I can come up with something like

```
    esize = [some formula] ! mnl: Estimate for B%n_s comes from YYYY paper by A, B, and C 
    esize = int(float(esize) * estsize_mult)
```

Also, instead of estimating the size would it be worth the memory overhead to just allocate more memory if we run out of room? Instead of throwing an error at line 2144, maybe do the following:
1. copy B%[row,col,n] into temp arrays
2. deallocate those three attributes of B
3. Increase esize (double? 1.5x?)
4. reallocate attributes of B
5. copy temp arrays back into B

Lastly, is esize ever written to output? I'm curious to see what the original esize was compared to the actual size of B%n_s once you increased estsize_mult to avoid the error.

**Comment by billsacks** [comment]
I absolutely agree with you on both counts:

(1) I tried figuring out what the current estimate was trying to accomplish, and gave up.

(2) I also considered the dynamic sizing that you suggest, but wasn't up for it myself. Seems we could use Sean's dynamic vector implementation here, although I don't know if you want that dependency in the mapping tool. But actually, the key part of the dynamic vector implementation that we'd need here just seems to be:

```
    ! Allocate new size
    allocate(tmp_array(capacity))
    ! Copy data
    tmp_array(:self%vec_size) = self%data(:self%vec_size)

    ! Replace array with new copy.
    deallocate(self%data)
    call move_alloc(tmp_array, self%data)
```

so I guess we could have a little routine that just does that.

(3) esize is written out if you exceed it. I have to run now, but could check my log files for the old vs. new esize.

Let me know if you'd like me to take a stab at the dynamic array resizing... it actually doesn't seem as bad as I originally thought it would be, and now I have some "truth" files to use as comparison.

**Comment by mnlevy1981** [comment]
I guess I shouldn't be surprised, but the papers behind these algorithms are a little tough to figure out... Edith Cohen seems to have been a big name in the field, and I found [http://www.cohenwang.com/edith/Papers/smm.pdf](Structure Prediction and Computation of Sparse Matrix Products) but I can't make heads or tails of it.

Given we want to find B = S \* A where S is `nocn` x `nocn` and A is `nocn` x `nrof` (with 1 non-zero entry per column) I think what we want is
1. Compute a `nrof` x `1` vector **a** such that _a(i)_ = number of non-zeros in row _i_ of A
2. compute matrix-vector product **b** = S' \* **a**, where S' has the same non-zero structure of S but all non-zero elements are set to 1 (so loop through S%row and S%col, but multiply by 1 instead of S%n)
3. esize = sum(**b**)

This shouldn't be terribly expensive - determining **a** may be tricky, but S' \* **a** will be significantly cheaper than the full S \* A multiply. I'll try to sketch something up tonight or in the morning and run it by you (or, more likely, let you know that it doesn't work)

edit: B = S \* A, not S = B \* A (hope I caught them all!)

**Comment by mnlevy1981** [comment]
Update: I forked @billsacks's fork and sent him a version of the algorithm outlined above - it works in the r05_g37 map case and isn't a performance concern (1 loop of A%n_s followed by 1 loop over S%n_s).

**Comment by billsacks** [comment]
Is there a reason to keep my original step3_estsize_mult now that you put in place your new code?

**Comment by billsacks** [comment]
I went ahead and removed my step3_estsize_mult, since it seems unnecessary: see the commit message for my last commit.

Let me know if you want me to restore this.

**Comment by billsacks** [comment]
As far as I'm concerned, this is ready to go now, but I'll leave the final call up to you, Mike.

**Comment by mnlevy1981** [comment]
I agree that estsize_mult is unnecessary given an exact computation of the size of B%n_s... if it turns out that this "exact computation" is not exact in some situations, we can always add estsize_mult back in.

**Comment by billsacks** [comment]
Okay, fixed the whitespace problems, and installed an emacs extension that (I think) will stop this from happening again. I think it should be good to go now.

**Pull request merged**
